#!/bin/bash

# Licensed under the MIT License. See the LICENSE accompanying this file
# for the specific language governing permissions and limitations under
# the License.

if [ "$#" -eq 1 ]; then
  INTERFACE="${1}"
else
  echo "usage: ${0##*/} <device name>"
  exit 1
fi

if [ $UID -ne 0 ]; then
  echo "error: ${0##*/} must be run as root"
  exit 1
fi

# Validate os-release
release=$(grep -P '^\ID=' /etc/os-release | tr -d 'ID=')
version=$(grep -oP "VERSION_ID=.\\K[0-9]+\\.[0-9]+" /etc/os-release | tr -d ".")
if [ ${release} == "ubuntu" ]; then
  if [ ${version} -lt 1804 ]; then
    echo "c2-ec2-netutils is not supported ubuntu version less than 18.04"
    exit 1
  fi
fi

. /etc/network/ec2net-functions

deactivate_primary
unplug_interface
