#!/bin/bash

# Licensed under the MIT License. See the LICENSE accompanying this file
# for the specific language governing permissions and limitations under
# the License.

if [ $UID -ne 0 ]; then
  echo "error: ${0##*/} must be run as root"
  exit 1
fi

# Validate os-release
release=$(grep -P '^\ID=' /etc/os-release | tr -d 'ID=')
if [ ${release} == "ubuntu" ]; then
  ubuntu_version=$(grep -oP "VERSION_ID=.\\K[0-9]+\\.[0-9]+" /etc/os-release | tr -d ".")
  if [ ${ubuntu_version} -lt 1804 ]; then
    echo "c2-ec2-netutils is not supported ubuntu version less than 18.04"
    exit 1
  fi
  int_name="ens"
  cfg_path="/etc/netplan"
  extension=".yaml"
fi

if [ ${release} == "debian" ]; then
  debian_version=$(grep -oP "VERSION_ID=.\\K[0-9]+" /etc/os-release)
  if [ ${debian_version} -lt 11 ]; then
    int_name="eth"
  else
    int_name="ens"
  fi
  cfg_path="/etc/network/interfaces.d"
  extension=".cfg"
fi

logger --tag ec2net "[ec2ifscan] Scanning for unconfigured interfaces"
for dev in $(find /sys/class/net/${int_name}*); do
  if [ ${dev##*/} == "eth0" ] || [ ${dev##*/} == "ens3" ]; then
    continue
  fi

  cfg="${cfg_path}/config-${dev##*/}${extension}"
  state=$(cat ${dev}/operstate)
  if [ ! -e "${cfg}" ] && [ "${state}" == "down" ]; then
    logger --tag ec2net "[ec2ifscan] Configuring ${dev##*/}"
      echo 'add' > ${dev}/uevent
  fi
done
