#!/bin/bash

release=$(grep -P '^\ID=' /etc/os-release | tr -d 'ID=')
if [ ${release} == "ubuntu" ]; then
  rm /etc/udev/rules.d/53-c2-network-interfaces.rules.debian
  rm /etc/udev/rules.d/75-persistent-net-generator.rules.debian
  mv /etc/udev/rules.d/53-c2-network-interfaces.rules.ubuntu /etc/udev/rules.d/53-c2-network-interfaces.rules
  mv /etc/udev/rules.d/75-persistent-net-generator.rules.ubuntu /etc/udev/rules.d/75-persistent-net-generator.rules
fi

if [ ${release} == "debian" ]; then
  version=$(grep -oP "VERSION_ID=.\\K[0-9]+" /etc/os-release)
  if [ ${debian_version} -lt 11 ]; then
    rm /etc/udev/rules.d/53-c2-network-interfaces.rules.ubuntu
    rm /etc/udev/rules.d/75-persistent-net-generator.rules.ubuntu
    rm /lib/udev/trigger-interface
    mv /etc/udev/rules.d/53-c2-network-interfaces.rules.debian /etc/udev/rules.d/53-c2-network-interfaces.rules
    mv /etc/udev/rules.d/75-persistent-net-generator.rules.debian /etc/udev/rules.d/75-persistent-net-generator.rules
  else
    # used ubuntu rules for debian because in version 11 interfaces was renamed from eth to ens
    rm /etc/udev/rules.d/53-c2-network-interfaces.rules.debian
    rm /etc/udev/rules.d/75-persistent-net-generator.rules.debian
    mv /etc/udev/rules.d/53-c2-network-interfaces.rules.ubuntu /etc/udev/rules.d/53-c2-network-interfaces.rules
    mv /etc/udev/rules.d/75-persistent-net-generator.rules.ubuntu /etc/udev/rules.d/75-persistent-net-generator.rules
  fi
fi

systemctl enable ec2net-scan.service
ln -s ec2ifup.8 /usr/share/man/man8/ec2ifdown.8

chmod 0644 /etc/network/ec2net-functions
chmod 0644 /lib/systemd/system/ec2net-scan.service
chmod 0755 /lib/udev/trigger-interface
chmod 0755 /lib/udev/write_net_rules
chmod 0755 /lib/udev/rule_generator.functions
chmod 0755 /usr/sbin/ec2ifup
chmod 0755 /usr/sbin/ec2ifdown
chmod 0755 /usr/sbin/ec2ifscan
